export * from './api.service';
import { ApiService } from './api.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './service.service';
import { ServiceService } from './service.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ApiService, CustomersService, ProfileService, ServiceService, UserService];
