/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentTypeEnum } from './commentTypeEnum';


export interface Comment { 
    readonly id: number;
    commentType: CommentTypeEnum;
    readonly updatedAt: string;
    comment: string;
    order: number;
    lastUpdateBy: number;
}

