/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CommentTypeEnum = 'Q' | 'E' | 'P' | 'T' | 'S' | 'O' | 'R' | 'J';

export const CommentTypeEnum = {
    Q: 'Q' as CommentTypeEnum,
    E: 'E' as CommentTypeEnum,
    P: 'P' as CommentTypeEnum,
    T: 'T' as CommentTypeEnum,
    S: 'S' as CommentTypeEnum,
    O: 'O' as CommentTypeEnum,
    R: 'R' as CommentTypeEnum,
    J: 'J' as CommentTypeEnum
};

