/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This serializer defines two fields for authentication:   * username   * password. It will try to authenticate the user with when validated.
 */
export interface Login { 
    username: string;
    password: string;
}

