/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ManagerEnum = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10';

export const ManagerEnum = {
    _1: '1' as ManagerEnum,
    _2: '2' as ManagerEnum,
    _3: '3' as ManagerEnum,
    _4: '4' as ManagerEnum,
    _5: '5' as ManagerEnum,
    _6: '6' as ManagerEnum,
    _7: '7' as ManagerEnum,
    _8: '8' as ManagerEnum,
    _9: '9' as ManagerEnum,
    _10: '10' as ManagerEnum
};

