/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusEnum } from './statusEnum';


export interface OrderAddendumList { 
    readonly id: number;
    readonly number: number;
    sequence: number;
    readonly __str__: string;
    description: string;
    trips: string;
    travelHours: string;
    laborHours: string;
    status?: StatusEnum;
    readonly statusDate: string;
}

