/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderAddendumDetail } from './orderAddendumDetail';


export interface OrderSequenceDetail { 
    readonly id: number;
    region: number;
    readonly number: number;
    addendum_set: Array<OrderAddendumDetail>;
}

