/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderSequenceList { 
    readonly id: number;
    readonly number: number;
    readonly region: string;
    jobSite: number;
    serviceCenter: number;
    billingCust: number;
}

