/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusEnum } from './statusEnum';


export interface OrderAddendumDetail { 
    readonly id: number;
    readonly number: number;
    description: string;
    laborHours: string;
    travelHours: string;
    trips: string;
    status?: StatusEnum;
    readonly statusDate: string;
    readonly item_set: Array<string>;
    readonly schedule_set: Array<string>;
}

