/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Technician } from './technician';


export interface PaginatedTechnicianList { 
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Technician>;
}

