/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedSchedule { 
    readonly id?: number;
    confirmed?: boolean;
    description?: string | null;
    startDate?: string;
    endDate?: string;
    startTime?: string;
    endTime?: string;
    travelHours?: string;
    addendum?: number | null;
    serviceCenter?: number;
    scheduledBy?: number | null;
    confirmedBy?: number | null;
    technicians?: Array<number>;
}

