/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegionEnum } from './regionEnum';


export interface Profile { 
    readonly id: number;
    region: RegionEnum;
    user: number;
    serviceCenter?: number | null;
}

