/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RegionEnum = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10';

export const RegionEnum = {
    _1: '1' as RegionEnum,
    _2: '2' as RegionEnum,
    _3: '3' as RegionEnum,
    _4: '4' as RegionEnum,
    _5: '5' as RegionEnum,
    _6: '6' as RegionEnum,
    _7: '7' as RegionEnum,
    _8: '8' as RegionEnum,
    _9: '9' as RegionEnum,
    _10: '10' as RegionEnum
};

