/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Schedule { 
    readonly id: number;
    confirmed?: boolean;
    description?: string | null;
    date?: string;
    startTime?: string;
    endTime?: string;
    travelHours: string;
    addendum?: number | null;
    serviceCenter: number;
    scheduledBy: number;
    confirmedBy?: number | null;
    technicians: Array<number>;
}

