/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ServiceCodeEnum = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12' | '13' | '14' | '15' | '16' | '17' | '18' | '19' | '20' | '21' | '22' | '23' | '24' | '25' | '26' | '27' | '28' | '29' | '30' | '31' | '32' | '33' | '34' | '35' | '36' | '37' | '38' | '39' | '40' | '41' | '42' | '43' | '44' | '45' | '46' | '47' | '48' | '49' | '50' | '51' | '52' | '53' | '54' | '55' | '56' | '99';

export const ServiceCodeEnum = {
    _1: '1' as ServiceCodeEnum,
    _2: '2' as ServiceCodeEnum,
    _3: '3' as ServiceCodeEnum,
    _4: '4' as ServiceCodeEnum,
    _5: '5' as ServiceCodeEnum,
    _6: '6' as ServiceCodeEnum,
    _7: '7' as ServiceCodeEnum,
    _8: '8' as ServiceCodeEnum,
    _9: '9' as ServiceCodeEnum,
    _10: '10' as ServiceCodeEnum,
    _11: '11' as ServiceCodeEnum,
    _12: '12' as ServiceCodeEnum,
    _13: '13' as ServiceCodeEnum,
    _14: '14' as ServiceCodeEnum,
    _15: '15' as ServiceCodeEnum,
    _16: '16' as ServiceCodeEnum,
    _17: '17' as ServiceCodeEnum,
    _18: '18' as ServiceCodeEnum,
    _19: '19' as ServiceCodeEnum,
    _20: '20' as ServiceCodeEnum,
    _21: '21' as ServiceCodeEnum,
    _22: '22' as ServiceCodeEnum,
    _23: '23' as ServiceCodeEnum,
    _24: '24' as ServiceCodeEnum,
    _25: '25' as ServiceCodeEnum,
    _26: '26' as ServiceCodeEnum,
    _27: '27' as ServiceCodeEnum,
    _28: '28' as ServiceCodeEnum,
    _29: '29' as ServiceCodeEnum,
    _30: '30' as ServiceCodeEnum,
    _31: '31' as ServiceCodeEnum,
    _32: '32' as ServiceCodeEnum,
    _33: '33' as ServiceCodeEnum,
    _34: '34' as ServiceCodeEnum,
    _35: '35' as ServiceCodeEnum,
    _36: '36' as ServiceCodeEnum,
    _37: '37' as ServiceCodeEnum,
    _38: '38' as ServiceCodeEnum,
    _39: '39' as ServiceCodeEnum,
    _40: '40' as ServiceCodeEnum,
    _41: '41' as ServiceCodeEnum,
    _42: '42' as ServiceCodeEnum,
    _43: '43' as ServiceCodeEnum,
    _44: '44' as ServiceCodeEnum,
    _45: '45' as ServiceCodeEnum,
    _46: '46' as ServiceCodeEnum,
    _47: '47' as ServiceCodeEnum,
    _48: '48' as ServiceCodeEnum,
    _49: '49' as ServiceCodeEnum,
    _50: '50' as ServiceCodeEnum,
    _51: '51' as ServiceCodeEnum,
    _52: '52' as ServiceCodeEnum,
    _53: '53' as ServiceCodeEnum,
    _54: '54' as ServiceCodeEnum,
    _55: '55' as ServiceCodeEnum,
    _56: '56' as ServiceCodeEnum,
    _99: '99' as ServiceCodeEnum
};

