/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StateEnum = 'AL' | 'AK' | 'AS' | 'AZ' | 'AR' | 'AA' | 'AE' | 'AP' | 'CA' | 'CO' | 'CT' | 'DE' | 'DC' | 'FL' | 'GA' | 'GU' | 'HI' | 'ID' | 'IL' | 'IN' | 'IA' | 'KS' | 'KY' | 'LA' | 'ME' | 'MD' | 'MA' | 'MI' | 'MN' | 'MS' | 'MO' | 'MT' | 'NE' | 'NV' | 'NH' | 'NJ' | 'NM' | 'NY' | 'NC' | 'ND' | 'MP' | 'OH' | 'OK' | 'OR' | 'PA' | 'PR' | 'RI' | 'SC' | 'SD' | 'TN' | 'TX' | 'UT' | 'VT' | 'VI' | 'VA' | 'WA' | 'WV' | 'WI' | 'WY';

export const StateEnum = {
    Al: 'AL' as StateEnum,
    Ak: 'AK' as StateEnum,
    As: 'AS' as StateEnum,
    Az: 'AZ' as StateEnum,
    Ar: 'AR' as StateEnum,
    Aa: 'AA' as StateEnum,
    Ae: 'AE' as StateEnum,
    Ap: 'AP' as StateEnum,
    Ca: 'CA' as StateEnum,
    Co: 'CO' as StateEnum,
    Ct: 'CT' as StateEnum,
    De: 'DE' as StateEnum,
    Dc: 'DC' as StateEnum,
    Fl: 'FL' as StateEnum,
    Ga: 'GA' as StateEnum,
    Gu: 'GU' as StateEnum,
    Hi: 'HI' as StateEnum,
    Id: 'ID' as StateEnum,
    Il: 'IL' as StateEnum,
    In: 'IN' as StateEnum,
    Ia: 'IA' as StateEnum,
    Ks: 'KS' as StateEnum,
    Ky: 'KY' as StateEnum,
    La: 'LA' as StateEnum,
    Me: 'ME' as StateEnum,
    Md: 'MD' as StateEnum,
    Ma: 'MA' as StateEnum,
    Mi: 'MI' as StateEnum,
    Mn: 'MN' as StateEnum,
    Ms: 'MS' as StateEnum,
    Mo: 'MO' as StateEnum,
    Mt: 'MT' as StateEnum,
    Ne: 'NE' as StateEnum,
    Nv: 'NV' as StateEnum,
    Nh: 'NH' as StateEnum,
    Nj: 'NJ' as StateEnum,
    Nm: 'NM' as StateEnum,
    Ny: 'NY' as StateEnum,
    Nc: 'NC' as StateEnum,
    Nd: 'ND' as StateEnum,
    Mp: 'MP' as StateEnum,
    Oh: 'OH' as StateEnum,
    Ok: 'OK' as StateEnum,
    Or: 'OR' as StateEnum,
    Pa: 'PA' as StateEnum,
    Pr: 'PR' as StateEnum,
    Ri: 'RI' as StateEnum,
    Sc: 'SC' as StateEnum,
    Sd: 'SD' as StateEnum,
    Tn: 'TN' as StateEnum,
    Tx: 'TX' as StateEnum,
    Ut: 'UT' as StateEnum,
    Vt: 'VT' as StateEnum,
    Vi: 'VI' as StateEnum,
    Va: 'VA' as StateEnum,
    Wa: 'WA' as StateEnum,
    Wv: 'WV' as StateEnum,
    Wi: 'WI' as StateEnum,
    Wy: 'WY' as StateEnum
};

