/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusEnum = '1' | '2' | '3' | '4' | '5';

export const StatusEnum = {
    _1: '1' as StatusEnum,
    _2: '2' as StatusEnum,
    _3: '3' as StatusEnum,
    _4: '4' as StatusEnum,
    _5: '5' as StatusEnum
};

