/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkWeek } from './workWeek';


export interface Technician { 
    readonly id: number;
    centers: Array<number>;
    qualifier?: string;
    type?: string;
    firstName: string;
    lastName?: string;
    readonly fullName: string;
    workWeek: WorkWeek;
    active?: boolean;
    schedules: Array<number>;
}

