/**
 * Service Calendar API
 * Mockup Service Calendar API
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WarrantyCodeEnum = '1' | '2' | '3' | '4' | '5' | '6' | '7';

export const WarrantyCodeEnum = {
    _1: '1' as WarrantyCodeEnum,
    _2: '2' as WarrantyCodeEnum,
    _3: '3' as WarrantyCodeEnum,
    _4: '4' as WarrantyCodeEnum,
    _5: '5' as WarrantyCodeEnum,
    _6: '6' as WarrantyCodeEnum,
    _7: '7' as WarrantyCodeEnum
};

